# Generated by Django 3.1.3 on 2021-03-29 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='')),
                ('anons', models.CharField(default='', max_length=160, verbose_name='')),
                ('full_text', models.TextField(default='', verbose_name='')),
                ('picture', models.FileField(default='', upload_to='pictures/', verbose_name='')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='')),
                ('current_user', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рисунок',
                'verbose_name_plural': 'Рисунки',
            },
        ),
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_content_meaning', models.IntegerField()),
                ('rate_draw_technique', models.IntegerField()),
                ('rate_originality', models.IntegerField()),
                ('evaluating_user', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('picture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view_pic.picture')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
    ]
