# Generated by Django 3.1.3 on 2021-05-31 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('view_pic', '0003_auto_20210531_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grading',
            name='picture_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='view_pic.picture'),
        ),
    ]
